name: base
channels:
  - defaults
  - conda-forge
dependencies:
  - python-kaleido
  - keras
  - numpy
  - optuna
  - pandas
  - plotly
  - pmdarima=2.0.4
  - pymongo=4.6.1
  - scikit-learn
  - scipy
  - statsmodels
  - tensorflow-gpu=2.13